//Declare and initialize LED pin variables
int LED_1 = 2;
int LED_2 = 3;
int LED_3 = 4;
//this variable will hold a random number generated by the random() function
long randomNumber;
void setup() {
Serial.begin(9600);
Serial.println("Starting new Random Number Sequence");
//set the LED pins as outputs
pinMode(LED_1, OUTPUT);
pinMode(LED_2, OUTPUT);
pinMode(LED_3, OUTPUT);
//Let's make it more random
randomSeed(analogRead(A0));}
void loop() {
//generate a random number
randomNumber = random(2,5);
Serial.print("The Random Number is = ");
Serial.println(randomNumber);
digitalWrite (randomNumber,HIGH);
delay(100);
digitalWrite (randomNumber,LOW);
delay(100);}